name: GitHub Actions

on:
  - push

jobs:
  run-gh-actions:
    runs-on: ubuntu-latest
    steps:
        - name: Simple JS Action
          id: greet
          uses: actions/hello-world-javascript-action@v1
          with:
            who-to-greet: ${{ github.actor }}
        - name: List of files
          run: |
            pwd
            ls -a
        - name: Checkout
          uses: actions/checkout@v2
        - name: List of Files after checkout
          run: |
            pwd
            ls
        - name: Get the output time
          run: echo "The time was ${{ steps.greet.outputs.time }}"
